#nullable enable

using HarmonyLib;

namespace AutoTerminalScanClassic.Interop.Game.Patches;

internal static class HarmonyPatchInstaller
{
    // MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Use it
    // here so the Harmony ID always matches the BepInEx plugin GUID.
    public static void Install()
    {
        var harmony = new Harmony(MyPluginInfo.PLUGIN_GUID);

        // PatchAll keeps patch discovery local to this assembly while this
        // boundary owns Harmony setup for the plugin entrypoint.
        harmony.PatchAll();
    }
}
