#nullable enable

using BepInEx;
using AutoTerminalScanClassic.Core.Ports;
using AutoTerminalScanClassic.Core.Validation;
using AutoTerminalScanClassic.Interop;
using AutoTerminalScanClassic.Interop.Game.Patches;

namespace AutoTerminalScanClassic;

/// <summary>
/// Controls who receives the generated scan-count chat message.
/// </summary>
/// <remarks>
/// The enum values are stored in the BepInEx config file, so names are part of
/// the user-facing configuration surface.
/// </remarks>
public enum BroadcastMode
{
    /// <summary>
    /// Show the scan result only in the local player's chat HUD.
    /// </summary>
    SelfOnly,

    /// <summary>
    /// Broadcast from hosts, while non-host clients keep the result local.
    /// </summary>
    HostOnly,

    /// <summary>
    /// Always request a server-backed chat message for all players.
    /// </summary>
    Always
}

/// <summary>
/// BepInEx plugin entrypoint for AutoTerminalScanClassic.
/// </summary>
/// <remarks>
/// MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Keep the
/// entrypoint metadata, Harmony ID, and startup log tied to that generated
/// plugin identity.
/// </remarks>
[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
[BepInProcess("Lethal Company.exe")]
public class AutoTerminalScanClassic : BaseUnityPlugin
{
    private static PluginController? controller;

    /// <summary>
    /// Shared plugin controller used by game callback types constructed outside startup.
    /// </summary>
    internal static PluginController Controller => controller!;

    private void Awake()
    {
        var logger = new BepInExPluginLogger(base.Logger);
        var config = BepInExPluginConfig.Bind(Config);

        // Validation logging is wired once at startup so Core can record
        // release-check events without branching at each call site.
        IValidationLogger validationLogger = config.ValidationLogging
            ? new BepInExValidationLogger(logger, System.DateTime.UtcNow)
            : DisabledValidationLogger.Instance;

        validationLogger.Record(
            ValidationLogRecord.PluginLoaded(
                version: MyPluginInfo.PLUGIN_VERSION,
                validationLogging: config.ValidationLogging,
                enabled: config.Enabled,
                broadcastMode: config.BroadcastMode
            )
        );

        // Create the workflow facade after BepInEx adapters are bound so Core
        // remains behind ports and does not read static plugin globals.
        controller = PluginController.Create(
            config: config,
            logger: logger,
            validationLogger: validationLogger
        );

        // Startup order matters: configure the guard after the controller is
        // wired and before patching so the first callback can be diagnosed.
        HarmonyCallbackGuard.Configure(
            new HarmonyCallbackDiagnosticReporter(
                logger: logger,
                validationLogger: validationLogger
            )
        );

        // Startup order matters: construct the controller before patching so
        // the first game callback can enter a fully wired plugin boundary.
        HarmonyPatchInstaller.Install();

        logger.LogInfo(
            $"Plugin {MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} is loaded!"
        );
    }
}
